sudo: false
language: python
python: 3.6
env:
  global:
  - 'SFTP_USER=[FTP_USER]'
  - 'SFTP_PASSWORD=[FTP_PASSWORD]'
  - 'SFTP_KEY=[base64-encoded-rsa-key]'

addons:
  apt:
    packages:
    - ncftp
    - pandoc
    - texlive-binaries
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - texlive-lang-german
    - latex-xcolor

install:
    - pip install pelican bibtexparser
script:
    - make html-cv

after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- cd output
- curl --ftp-create-dirs
       -T index.html
       --key /tmp/sftp_rsa
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@ftp.fwagner.info
